### PR TITLE
Sphinx site

### LINKED ISSUE #12: How to host our documentation
A major goal of this project is basically producing a ton of documentation. Eventually I envision an online resource consisting of:

* Documentation on how to deploy a "pangeo environment" (including distributed cluster) in various contexts such as
  - different clusters (Cheyenne [[already started](https://github.com/pangeo-data/pangeo-discussion/wiki/Getting-Started-with-Dask-on-Cheyenne)], [Gaea](https://www.ncrc.gov/gaea/), [Pleiades](https://www.nas.nasa.gov/hecc/resources/pleiades.html), etc.)
  - generic local cluster
  - cloud environment
* Guides for system administrators about how to support pangeo environment
* Domain-specific tutorials based on the use-cases (e.g. #1, #11)
* Benchmarking results

Our [wiki](https://github.com/pangeo-data/pangeo-discussion/wiki) is useful for getting info online fast, but it might not be the best option for scaling up. It's not scriptable, PR-able, etc. And it can't easily import jupyter notebooks.

Some options for moving forward are:

* Just keep the github wiki as the central pangeo documentation resource.
* Use the [Pangeo jeykll site](http://pangeo-data.github.io) ([repo](https://github.com/pangeo-data/pangeo-data.github.io)).
* Develop a [sphinx site](http://www.sphinx-doc.org/en/stable/index.html) for our documentation.

There are pros and cons to each. I'm curious to hear your thoughts.

### PR DESCRIPTION
**Pull request by rabernat**
I am eager to get this sphinx documentation site going, so I set it up myself.

fixes #12

### CODE REVIEW

**Comment by dopplershift** [comment]
Sorry I hadn't been able to get around to this...

**Comment by rabernat** [comment]
I'm currently stuck on drdoctr/doctr#277.

**Comment by dopplershift** [comment]
Try rebuilding—looks like a new release of doctr is available and should fix it.

**Comment by rabernat** [comment]
There is a lot to review here..I am thinking I will just merge this and get a version of the docs online so we can all see what I have done.

@dopplershift any comments before I merge?

**Comment by dopplershift** [comment]
Go for it!

**Comment by mrocklin** [comment]
Where did this get hosted?

**Comment by rabernat** [comment]
pangeo-data.github.io/pangeo

...For now. At some point we should homogenize our web presence.

**Pull request merged**
