### PR TITLE
Add Pangeo helm chart

### LINKED ISSUE #178: Create an official helm chart
Pangeo is effectively comprised of the [zero-to-jupyterhub helm chart](https://zero-to-jupyterhub.readthedocs.io/en/latest/) (`jupyterhub/jupyterhub`) with a custom Docker image and additional configuration.

As some of the packages within the custom Docker image may require extra kubernetes resources (such as RBAC roles for dask-kubernetes in #172 ) it would be sensible to create a pangeo helm chart which inherits ([docs on inheritance](https://docs.helm.sh/developing_charts/#chart-dependencies)) from zero-to-jupyterhub. This allows Pangeo to be installed as a single chart that includes any Pangeo specific resources.

At the Met Office we currently have a [`jadepangeo` helm chart](https://github.com/met-office-lab/jade-pangeo) which inherits from `jupyterhub/jupyterhub` and adds some extra manifests for RBAC, domain redirection and monitoring. I would like to get to a position where our chart depends on a Pangeo chart instead as it would allow me to move things upstream more easily. 

It would be good for the chart to be called `pangeo/pangeo` which would allow us to sensibly rename `jadepangeo` to `metoffice/pangeo`, as the Pangeo project has superseded the Jade project now.

The current `jadepangeo` chart would make a good starting point so I'll look at making it more generic and getting that into this repo.

### PR DESCRIPTION
**Pull request by jacobtomlinson**
**This PR has resulted in the creation of pangeo-data/helm-chart#1, chart specific discussion has moved there.**

This PR is a work in progress and I'm keen on discussion and debate to help shape it. The primary goals here are to create a new helm chart for Pangeo which wraps up dependent charts (currently just [zero-to-jupyterhub](https://github.com/jupyterhub/zero-to-jupyterhub-k8s)) with extra kubernetes resources to tie everything together. This PR updated the pangeo deployment to use pangeo-data/helm-chart.

### Things implemented in this PR
- [x] Update the GCE instructions to point to the new chart.
- [x] Indent current helm config under a `jupyterhub` key as per the [helm documentation for dependencies](https://docs.helm.sh/developing_charts/#chart-dependencies).

### Discussion points
- ~~Are we happy for this to be placed in this repository, or should it be a separate one?~~
- Helm charts can be published as static files at an arbitrary URL which would facilitate the below installation example. Where should we publish the charts? 
```shell
helm repo add pangeo <some URL>
helm repo update
helm install pangeo/pangeo --name=pangeo --namespace=pangeo -f values.yaml
```
  
Closes #178

### CODE REVIEW

**Comment by rabernat** [comment]
Thanks @jacobtomlinson for this fantastic contribution!  🥇 

> Are we happy for this to be placed in this repository, or should it be a separate one?

I am fine with it living here for now. Eventually, we want to think about how to fragment this main repository into the optimal standalone bits. But doing so now seems premature.

> Helm charts can be published as static files at an arbitrary URL which would facilitate the below installation example. Where should we publish the charts?

We could hypothetically serve them as part of the sphinx documentation as static files. Then they would be accessible via the pangeo-data.github.io url. What is the standard practice for serving helm charts?

Unfortunately, I can't offer much insight on RBAC as I don't understand these aspects of kubernetes.

**Comment by mrocklin** [comment]
This seems fine to me.  I'd be comfortable using the gh-pages branch of this repository as the helm repository for now.  I suspect that eventually we'll want to peel off all of the Kubernetes/cloud-based work to another repository in the future though once things stabilize.

I suspect that over time the values.yaml file will become less sparse.

**Comment by rabernat** [comment]
> I'd be comfortable using the gh-pages branch of this repository as the helm repository for now.

That is where the sphinx site currently lives: https://pangeo-data.github.io/pangeo/

**Comment by mrocklin** [comment]
Ah, we're self-hosting and not using readthedocs?

**Comment by rabernat** [comment]
Correct. That could be changed of course.

**Comment by mrocklin** [comment]
Maybe that's just extra motivation to start fresh in a new repository?

**Comment by jacobtomlinson** [comment]
I'm happy either way. Helm repositories are just web servers with zipped up helm charts and an `index.yaml` file describing them. So it would be easy to integrate into a sphinx or jekyll site. However it may be simpler to just start fresh in a new repo.

**Comment by rabernat** [comment]
I think it makes sense to start a new repo within the pangeo-data organization for our helm charts.

I have created a new repo for the helm-chart
https://github.com/pangeo-data/helm-chart

I have also created a new team within the organization called @pangeo-data/pangeo-admin. These people have admin rights on the helm-chart repo. In the future, I would like to start using this team for all things that require deploy permissions for pangeo.pydata.org.

**Comment by jacobtomlinson** [comment]
Ok great! I have moved the chart itself into pangeo-data/helm-chart#1. This PR is now just an update to the gce scripts to make use of the new chart instead of `z2jh`.

**Comment by jacobtomlinson** [comment]
I have just removed some values from the `jupyter-config.yaml` file as they are going to be default values in the helm chart.

Ideally I would like to shrink `jupyter-config.yaml` further until it just contains things which are specific to this deployment of pangeo. This would probably just be GCE specific settings and authentication secrets for pangeo.pydata.org.

Some things like the branding will need kubernetes/helm#3767 to be resolved before they can be moved over.

**Comment by jacobtomlinson** [comment]
I'm pretty happy with this now so I'm going to update pangeo.pydata.org with the new chart. I've gotten as far as configuring my `gcloud` and `kubectl` settings but I need the `SECRET` values which have been omitted from the config. Could someone please provide them to me?

@mrocklin @rabernat @jhamman

**Comment by mrocklin** [comment]
Done

**Comment by jacobtomlinson** [comment]
I tried upgrading the cluster to this version but I got this error from helm.

```
Error: UPGRADE FAILED: no PodDisruptionBudget with the name "hub" found
```

Looking back at the logs it looks like that has happened before so perhaps someone has some insight on what I did wrong.

I tried rolling back to the previous deployment but for some reason that didn't work so I deployed the version from the master branch.

Someone who has deployed this before (@mrocklin) may wish to take a look at the stack to ensure I correctly put it back together and that it is usable.

I'll look at this again tomorrow.

**Comment by rabernat** [comment]
I believe the cluster is now broken. I am unable to start my server because my `jupyter-rabernat` pod won't start:
https://console.cloud.google.com/kubernetes/pod/us-central1-b/pangeo/pangeo/jupyter-rabernat?project=pangeo-181919&tab=events&duration=PT1H&container_summary_list_tablesize=10&jupyter-rabernat_events_tablesize=50

image

I believe the core error is the `InvalidImageName`

**Comment by mrocklin** [comment]
I've run into InvalidImageName before and resolved it just by trying to
redeploy a couple of times, sometimes with different versions of
jupyterhub.  My apologies for not having a better answer here.  This is
something that we should probably track down.

It's also worth noting that we're currently deployed on some random commit
of JupyterHub.  It might be worth looking into a cleaner dependence at some
point.

**Comment by mrocklin** [comment]
> Error: UPGRADE FAILED: no PodDisruptionBudget with the name "hub" found

I've never seen this error myself.  Though enough things have happened that I am not surprised to learn that it may have been generated on my behalf.

**Comment by jhamman** [comment]
I have a short presentation in about 90 minutes where I was planning on highlight the GCE deployment. Not a big deal if its not possible, but if someone has the bandwidth to redeploy the cluster so that it "works", that would be great. I'm personally unavailable between now and then.

**Comment by mrocklin** [comment]
Doing that now.  We'll see what happens

**Comment by mrocklin** [comment]
I've thrashed around a lot and things seem to be up.  The notebook image is having trouble with gcs though, so maybe it's not the most recent image.  @jhamman I recommend playing around.

**Comment by mrocklin** [comment]
I'm now getting the following when I try to upgrade

```
mrocklin@carbon:~/workspace/helm-chart$ helm upgrade jupyter pangeo/ -f jupyter-config.yaml 
2018/03/28 15:53:11 warning: cannot overwrite table with non table for extraConfig (map[])
2018/03/28 15:53:11 warning: cannot overwrite table with non table for extraConfig (map[])
Error: UPGRADE FAILED: no ServiceAccount with the name "pod-culler" found
```

However things seem to be ok except for gcsfs.  I've recommended that @jhamman both install gcsfs from git master in his notebook pod

    pip install git+https://github.com/dask/gcsfs@master --upgrade --no-deps

and add this to his worker-template.yaml file under `env:`

      - name: EXTRA_PIP_PACKAGES
        value: git+https://github.com/dask/gcsfs@master --upgrade --no-deps

I've pushed up a new notebook and worker image with this built in, but am having difficulty upgrading as noted above

**Comment by mrocklin** [comment]
New notebook image is `pangeo/notebook:2018-03-28`

**Comment by jacobtomlinson** [comment]
Thanks for resolving that. Sorry for causing problems!

I'll update the notebook image version in the helm chart too.

I'm going to look at trying to upgrade to this branch again today. I might create a dev stack somewhere for experimenting first though.

**Comment by jacobtomlinson** [comment]
It looks like we may be coming across a bug in helm. When I run the upgrade I get this error 

```
Error: UPGRADE FAILED: no ServiceAccount with the name "pod-culler" found
```

However when listing the service accounts it definitely exists

```
$ kubectl -n pangeo get serviceaccounts                                                   
NAME                                       SECRETS   AGE
daskkubernetes                             1         4m
default                                    1         82d
hook-image-awaiter-jupyter-91-1522266556   1         14h
hub                                        1         14h
pod-culler                                 1         1m
proxy                                      1         14h
```

If I delete the service account it gets recreated and moves on to the next error which is not being able to find the `daskkubernetes` service account. Removing that leads me to not being able to find the `pud-culler` role. I seem to not have permission to delete roles and so I cannot troubleshoot any further.

I expect an immediate fix would be to delete everything which is showing as missing and that should cause the deployment to succeed. But the long term fix is for helm/tiller to correctly locate these resources.

**Comment by jacobtomlinson** [comment]
A clean install into a new namespace works with no issues.

**Comment by mrocklin** [comment]
People have been having issues with 2.8 ?  Perhaps roll back to 2.7?

I've also elevated your permissions

**Comment by jacobtomlinson** [comment]
I don't think my permissions have been elevated correctly, I am not unable to delete service accounts either.

**Comment by jacobtomlinson** [comment]
I have successfully deployed this branch to pangeo.pydata.org. Sadly I accidentally caused a refresh of the load balancer which changed the IP address of the service.

@mrocklin has requested that pangeo.pydata.org be updated to the new address. For testing until that has happened you can add `35.226.234.19	pangeo.pydata.org` to your `/etc/hosts` file.

I have successfully logged in, started a server and used `dask-kubernetes` to create workers. Therefore I am happy for this branch to be merged now. However I'm happy to wait until the global DNS has updated is people prefer.

**Comment by mrocklin** [comment]
It's a development system.  I'm fully in favor of moving quickly even if it
means breaking things.  I'm *really *grateful to you that you've been doing
this work.

**Comment by jacobtomlinson** [comment]
Ok great. I'll merge this now then.

**Comment by rabernat** [comment]
Even with the `/etc/hosts` hack, I am not able to get my server going. I got to the landing page, but after trying to authenticate with github, I got
> 400 : Bad Request
> OAuth state missing from cookies

**Comment by mrocklin** [comment]
Anaconda IT has updated the DNS entry.  Things should operate normally now.

**Pull request merged**
