### PR TITLE
How to bump version

### PR DESCRIPTION
**Pull request by jbusecke**
From the text it was not completely clear how to bump the version of a package in the image. I hope this will help. 

Should these issue be raised in this repo? Or elsewhere?

### CODE REVIEW

**Comment by jbusecke** [comment]
cc @cspencerjones

**Comment by jbusecke** [comment]
Do folks think this is helpful/still required? Otherwise I can also close the PR.

**Comment by cspencerjones** [comment]
I think yes! It is helpful to have this.

**Comment by jbusecke** [comment]
Just wanted to ping this, if still relevant @pangeo-data/pangeo-admin

**Comment by jbusecke** [comment]
Is this still relevant?

**Comment by jbusecke** [comment]
I am closing this due to a lack of activity for now.

**Pull request closed without merging**
