### PR TITLE
remove docker images from repo

### PR DESCRIPTION
**Pull request by rabernat**
They have moved to https://github.com/pangeo-data/helm-chart.

### CODE REVIEW

**Comment by jhamman** [comment]
One thought I'm having: should we move the example notebooks to an independent repo?

**Comment by mrocklin** [comment]
I'm in favor of this.  I also think that we should just copy this repo into
the user space on every load.

**Comment by rabernat** [comment]
> I also think that we should just copy this repo into
> the user space on every load.

Is "this" referring to hypothetical new repository with example notebooks? If so, I agree.

**Comment by mrocklin** [comment]
yes

**Pull request merged**
