### PR TITLE
add gmet zarr dataset to intake cat

### PR DESCRIPTION
**Pull request by jhamman**
xref: https://github.com/pangeo-data/pangeo-example-notebooks/pull/5

### CODE REVIEW

**Comment by martindurant** [comment]
I am +1 for this.
However, the full dataset contains rather a lot of files and is slow to load the metadata. The chunksize of 14MB is OK order-of-magnitude but perhaps would be better at ~100MB. Perhaps this data-set also needs the metadata treatment in https://github.com/pangeo-data/pangeo/issues/309 , and a general agreement on how to cope with the many-files problem for the future (half-million files in this case).

**Comment by jhamman** [comment]
@martindurant - I can update the chunksize in the dataset if that would be useful.

**Comment by martindurant** [comment]
I certainly think that would help, and ~> 100MB is a good place to aim, perhaps bigger as the total dataset increases.

**Comment by jhamman** [comment]
Right. I may remove the .zarr suffix though. Thoughts?

**Comment by mrocklin** [comment]
> Perhaps this data-set also needs the metadata treatment in #309

How does one do this?  Do we need a best practices doc?  Should this be
upstreamed to XArray in some way?

**Comment by martindurant** [comment]
@mrocklin , right, it's strictly ad-hoc, we didn't come to  a conclusion on how to consolidate the metadata in a way to causes least friction. My simplistic solution was to put a file `.zmetadata` in the top-level with the contents of all of the rest of the `.z*` files in the hierarchy; then `zarr.Group` looks for this key in the mapping. Following the discussion on metadata over on zarr, it could, for example, have been an additional entry in `.zattrs` in the top-level, and so stay within the spec.

**Comment by martindurant** [comment]
(but yes, it could have been a PR to xarray, that's part of the conversation in #309)

**Comment by martindurant** [comment]
> I may remove the .zarr suffix though on the bucket. Thoughts?

I mildly side with keeping it, for people that browse the file hierarchy in the bucket.

**Comment by mrocklin** [comment]
OK.  I'd like to make sure that if this is important that it doesn't get
lost.  It looks like nothing significant has happened on that issue for
about a month.  @martindurant do you have thoughts on the right way to come
to some long-term conclusion on this issue?  Should it be elevate to some
upstream issue tracker?

**Comment by martindurant** [comment]
We have https://github.com/zarr-developers/zarr/pull/268 , which is also getting old.

**Comment by alimanfoo** [comment]
Happy to pick that discussion up again on the Zarr side if that would help.

**Comment by jhamman** [comment]
I rechunked the dataset. We're down to 16k chunks and up to ~80mb/chunk.

**Pull request merged**
