### PR TITLE
Render examples in docs with sphinx-nbexamples

### PR DESCRIPTION
**Pull request by Chilipp**
Hey all together!

In reference to https://github.com/pangeo-data/pangeo/issues/201 this PR adds the basic setup for rendering the examples in the docs using the [sphinx-nbexamples](http://sphinx-nbexamples.readthedocs.io/en/latest/index.html) package.
I changed the doctr secure variable in `.travis.yml` to deploy to https://chilipp.github.io/pangeo/. So **do not simply merge this PR**, it first has to be changed back.

The rendered examples can be seen in https://chilipp.github.io/pangeo/use_cases/index.html
So far, this is just a short demonstration of how it would look like. I did not change any content, I just renamed some files (`docs/use_cases` to `use_cases` and `use_cases/index.rst` to `use_cases/README.rst`) to make sphinx-nbexamples working. On Travis, `docs/use_cases` is generated by sphinx-nbexamples.

I can also add some more features to sphinx-nbexamples, since I am always willing to add new features and improve the package.

Open points from my point of view here are:

- [x] Some titles need to be changed for the examples because they are too long and this does not look good in the thumbnails (or I modify sphinx-nbexamples to truncate the title)
- [x] Every example should have a short summary (one paragraph after the first heading in the notebook) that is highlighted in the tooltip when you hover over the example. At the moment, this is a rather large description or some other informations.
- [ ] the *CESM Large Ensemble Tracer Budget* example requires an image to be displayed in [the gallery](https://chilipp.github.io/pangeo/use_cases/index.html). This can either be created in the notebook itself, or we can select any other image (see [Choosing the thumbnail](http://sphinx-nbexamples.readthedocs.io/en/latest/getting_started.html#choosing-the-thumbnail))
- [x] Which examples should be processed at every build of the docs? At the moment, I disabled the preprocessing for all examples (see the [conf.py](https://github.com/pangeo-data/pangeo/compare/master...Chilipp:master#diff-85987f48f1258d9ee486e3191495582dR42)) but this should be changed to always execute the notebooks when generating the docs.
- [x]  Should the example thumbnails be displayed on the the [main page](https://chilipp.github.io/pangeo/) as well? Such as [in the psyplot docs](http://psyplot.readthedocs.io/en/latest/#examples)?
- [x] Do we stick to the current directory structure? As there are examples in the [docs/use_cases](https://github.com/pangeo-data/pangeo/tree/master/docs/use_cases) (or use_cases) directory and in [notebooks](https://github.com/pangeo-data/pangeo/tree/master/notebooks) directory

pinging @rabernat and @jhamman

### CODE REVIEW

**Comment by rabernat** [comment]
@Chilipp this looks incredibly cool. Thank you so much for putting this together!

I don't have time this week to provide a detailed review, but all the issues you raise seem reasonable. I would not hesitate the rewrite the text within the notebooks and reorganize them as you see fit. Perhaps we will want to provide a template for other future use cases to follow.

**Comment by jhamman** [comment]
+1 on changing whatever text/titles/summary makes sense. If you need text/summaries for particular examples, feel free to ping the authors here.

> Should the example thumbnails be displayed on the the main page as well?

Yes, it would be nice if we can fix up the thumbnails a bit so they are not transparent but for now, I think they are fine.

> Which examples should be processed at every build of the docs?

I think basically none. At least for now.

**Comment by rabernat** [comment]
Let's get this moving forward. Sorry for my delay! This will be a very useful upgrade to our website.

My main comment is that https://chilipp.github.io/pangeo/use_cases/index.html is a bit confusing because the notebooks are basically listed twice. I would eliminate the toctree from the index page and just show the gallery.

Is it possible to have the gallery organized into sub-sections? Currently we have "physical oceanography", "meteorology", and "climate modeling". Is there a way to keep these heading but then have the notebook preview links appear under them? Do we need subfolders for that.

Please feel free to just reformat the notebooks to make them look better. If you need summary paragraphs, let's get them from the original authors (myself, @jhamman, and @sridge).

**Comment by Chilipp** [comment]
> Is it possible to have the gallery organized into sub-sections? Currently we have "physical oceanography", "meteorology", and "climate modeling". Is there a way to keep these heading but then have the notebook preview links appear under them? Do we need subfolders for that.

Yes, indeed. We would need one folder for each of the subsections. The directory structure would then need to be like

```
use_cases/
├── README.rst
├── climate\ modeling
│   ├── CESM-Large-Ensemble-Tracer-Budget-Example.ipynb
│   └── README.rst
├── meteorology
│   ├── README.rst
│   └── newmann_ensemble_meteorology.ipynb -> ../notebooks/newmann_ensemble_meteorology.ipynb
└── physical\ oceanography
    ├── README.rst
    └── sea-surface-height.ipynb
```

**Comment by rabernat** [comment]
This sounds like the way to go!

It would be wonderful if you could set it up that way and update your PR. Feel free to put in your own interpretations of the notebook content for the intro paragraphs. We can always update these later on.

**Comment by Chilipp** [comment]
Sure! Concerning @jhamman [comment](https://github.com/pangeo-data/pangeo/pull/317#issuecomment-398937286):

> > Should the example thumbnails be displayed on the the main page as well?
>
> Yes, it would be nice if we can fix up the thumbnails a bit so they are not transparent but for now, I think they are fine.

I am not sure, what you mean with *transparent*. Because the thumbnail is not transparent. Do you mean the container around the thumbnail? To avoid issues like this in the [example gallery](https://chilipp.github.io/pangeo/use_cases/index.html)?
image
Here the title of the example is too long for the container. So the easiest way to avoid this effect is to shorten the title of the notebook (or to make changes in the [CSS file for sphinx-nbexamples](https://github.com/Chilipp/sphinx-nbexamples/blob/master/sphinx_nbexamples/_static/example_gallery_styles.css) to fit the container height to it's content)

**Comment by Chilipp** [comment]
ok, so here we are:

In order to have better titles and tooltips for the [examples](https://chilipp.github.io/pangeo/use_cases/index.html#use-cases), I changed some intros:

- [ ] @jhamman  and @mrocklin: For the US Precipitation and Temperature analysis example. Could you please review https://github.com/pangeo-data/pangeo/pull/317/commits/da7bf89b3a060ac68cc529d9af78b3ef4ba164c1? 
- [ ] @rabernat: For the sea surface altimetry example. Could you please review https://github.com/pangeo-data/pangeo/pull/317/commits/41378c5735d98c70669be39abd9b0731b82e4e79?
- [ ] @jhamman and @sridge: For the CESM example on the DIC budget: Could you please review https://github.com/pangeo-data/pangeo/pull/317/commits/2a4b304464f364dc6c011ecef728e6de72fd68c6? Also, can you please think of a nice image that we can use to display the example in the example gallery?

I also changed the directory structure as mentioned above in https://github.com/pangeo-data/pangeo/pull/317#issuecomment-401084113. 

Thanks all for your input on this! When these changes are approved, I can prepare this branch for being merged with the upstream master (i.e. I change again the secure variable for doctr in the `.travis.yml` file). But of course, if there is more to it, just tell me 😄

**Comment by rabernat** [comment]
Sorry to let this sit for so long.

I'm very happy with this and ready for it to be merged. @Chilipp, please let us know when the travis config has be reset such that this is merge-ready.

**Comment by Chilipp** [comment]
Hey! No problem, it didn't cost a lot of my time :smile:

> @Chilipp, please let us know when the travis config has been reset such that this is merge-ready.

Done by https://github.com/pangeo-data/pangeo/pull/317/commits/8206443fa09294b821bc92ddb71f0bbf7eb4da8b

> the CESM Large Ensemble Tracer Budget example requires an image to be displayed in the gallery. This can either be created in the notebook itself, or we can select any other image (see [Choosing the thumbnail](http://sphinx-nbexamples.readthedocs.io/en/latest/getting_started.html#choosing-the-thumbnail))

This is the only thing that is still missing from my point of view, but if you are happy with this, it's ready to be merged

**Comment by rabernat** [comment]
> This is the only thing that is still missing from my point of view, but if you are happy with this, it's ready to be merged

I think we can live with that for now.

Unfortunately something has gone stale and there is now a merge conflict. Any chance you can resolve?

Sorry again for being so slow to iterate on this PR.

**Pull request merged**
