### PR TITLE
big catalog update

### PR DESCRIPTION
**Pull request by rabernat**
This PR adds many ocean datasets to our intake catalog which have been there for a while but have not been easily discoverable.

### CODE REVIEW

**Comment by rabernat** [comment]
The travis build failed with this error:
```
Exception occurred:
  File "/home/travis/miniconda/envs/docs-environment/lib/python3.6/site-packages/intake/catalog/local.py", line 155, in __init__
    self._plugin = global_registry[driver]
KeyError: 'netcdf'
The full traceback has been saved in /tmp/sphinx-err-27qz74o5.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [html] Error 1
```

However, this doesn't seem related to my PR, since I didn't add any datasets with the netcdf driver. That was already in there:
https://github.com/pangeo-data/pangeo/blob/b60e932f7307c4d484337d4da1e3842037362d51/gce/catalog.yaml#L5-L12

**Comment by martindurant** [comment]
Passing now. Needed a re-release of Intake. Not sure what was going on, should check that the netcdf sources actually load, rather than getting skipped.

**Comment by rabernat** [comment]
cool, thanks martin!

Anyone else have comments before I merge?

(Ideally we should do this for all the datasets, but I just want to get the ball rolling.)

**Comment by martindurant** [comment]
As far as I can tell, it look fine. The proof is in testing within a running instance.

Do you make use of the metadata tags? Perhaps those can be rendered on the catalog HTML page.

**Comment by rabernat** [comment]
Yes, eventually I would like to use the metadata tags for various purposes.

**Pull request merged**
