### PR TITLE
Document installing packages on workers

### PR DESCRIPTION
**Pull request by TomAugspurger**
cc @jbusecke

### CODE REVIEW

**Comment by jbusecke** [comment]
outstanding! Thanks a ton, @TomAugspurger. Would this also work with conda?

**Comment by TomAugspurger** [comment]
FYI, https://github.com/dask/distributed/pull/3216 was merged into distributed and will be in the next release.

I plan to update these docs to point to that when it's available.

Nothing for conda yet. It could be done, but the longer solve times for conda means the downsides of this general approach will be felt even more. I'd recommend just layering pip packages (ideally pure python, with simple dependencies) on top of the base environment for now. More complicated things should probably go in the base environment. Happy to hear of use-cases where conda installing on worker startup would genuinely be useful.

**Comment by jbusecke** [comment]
That sounds good. I will try these out in the next days, but [ocean parcels](https://github.com/OceanParcels/parcels) with its extensive dependencies seems like a candidate for the base env.

**Comment by rabernat** [comment]
Thanks for this!

**Comment by jbusecke** [comment]
I am still trying to get [parcels]() installed on dask workers, but there seem to be some issues with adding it to the main notebook for now (see [pangeo-docker-images/162](https://github.com/pangeo-data/pangeo-docker-images/pull/162#issuecomment-727060809)).
I just tried to modify your instructions [here](https://pangeo.io/cloud.html#dask-software-environment) naively to run a conda install on the workers (for this testing case I do not care how slowly they start):

```python
import subprocess
import logging
from distributed import WorkerPlugin

class CondaPlugin(WorkerPlugin):
    """
    Install packages on a worker as it starts up.

    Parameters
    ----------
    packages : List[str]
        A list of packages to install with pip on startup.
    """
    def __init__(self, packages):
        self.packages = packages

    def setup(self, worker):
        logger = logging.getLogger("distributed.worker")
        subprocess.call(['python', '-m', 'conda', 'install', '-c','conda-forge', '-y'] + self.packages)
        logger.info("Installed %s", self.packages)


cluster = GatewayCluster()
client = cluster.get_client()
plugin = CondaPlugin(['parcels'])
client.register_worker_plugin(plugin)
```
This just gives me `{}` as output and when I run the suggested test:

```python
def check():
    import parcels
    return parcels.__version__

cluster.scale(2)
client.wait_for_workers(2)
client.run(check)
```

I get an error that `parcels` is not installed.

```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-11-5fe8b4c872c1> in <module>
      1 cluster.scale(2)
      2 client.wait_for_workers(2)
----> 3 client.run(check)

/srv/conda/envs/notebook/lib/python3.8/site-packages/distributed/client.py in run(self, function, *args, **kwargs)
   2510         >>> c.run(print_state, wait=False)  # doctest: +SKIP
   2511         """
-> 2512         return self.sync(self._run, function, *args, **kwargs)
   2513 
   2514     def run_coroutine(self, function, *args, **kwargs):

/srv/conda/envs/notebook/lib/python3.8/site-packages/distributed/client.py in sync(self, func, asynchronous, callback_timeout, *args, **kwargs)
    830             return future
    831         else:
--> 832             return sync(
    833                 self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
    834             )

/srv/conda/envs/notebook/lib/python3.8/site-packages/distributed/utils.py in sync(loop, func, callback_timeout, *args, **kwargs)
    338     if error[0]:
    339         typ, exc, tb = error[0]
--> 340         raise exc.with_traceback(tb)
    341     else:
    342         return result[0]

/srv/conda/envs/notebook/lib/python3.8/site-packages/distributed/utils.py in f()
    322             if callback_timeout is not None:
    323                 future = asyncio.wait_for(future, callback_timeout)
--> 324             result[0] = yield future
    325         except Exception as exc:
    326             error[0] = sys.exc_info()

/srv/conda/envs/notebook/lib/python3.8/site-packages/tornado/gen.py in run(self)
    733 
    734                     try:
--> 735                         value = future.result()
    736                     except Exception:
    737                         exc_info = sys.exc_info()

/srv/conda/envs/notebook/lib/python3.8/site-packages/distributed/client.py in _run(self, function, nanny, workers, wait, *args, **kwargs)
   2447             elif resp["status"] == "error":
   2448                 typ, exc, tb = clean_exception(**resp)
-> 2449                 raise exc.with_traceback(tb)
   2450         if wait:
   2451             return results

<ipython-input-4-eb08265a7c4b> in check()
      1 def check():
----> 2     import parcels
      3     return parcels.__version__

ModuleNotFoundError: No module named 'parcels'
```

@TomAugspurger do you think there is any way to make this work? Atm I don't care about how long the worker needs to start up, Id just like to be able to test whether running lagrangian particles on dask works (and then the situation would be solved by [pangeo-docker-images/162](https://github.com/pangeo-data/pangeo-docker-images/pull/162#issuecomment-727060809)) or if more work is needed.

**Comment by dcherian** [comment]
@jbusecke have you seen https://discourse.pangeo.io/t/coordinating-efforts-on-lagrangian-filtering-for-swot/928/7?

**Comment by jbusecke** [comment]
No I did not yet. Thanks for the heads-up! Ill try to read through that soon. cc @gmacgilchrist

**Comment by scottyhq** [comment]
@jbusecke I think conda is timing out solving the environment - I've never understood what to make of messages like this
```
Collecting package metadata (current_repodata.json): done
Solving environment: \ 
The environment is inconsistent, please check the package plan carefully
The following packages are causing the inconsistency:

  - conda-forge/linux-64::cartopy==0.18.0=py38h4f3c6b6_2
  - conda-forge/noarch::dask-glm==0.2.0=py_1
  - conda-forge/noarch::dask-ml==1.7.0=py_0
  - conda-forge/noarch::datashader==0.11.1=pyh9f0ad1d_0
  - conda-forge/noarch::geoviews-core==1.8.2=py_0
  - conda-forge/noarch::metpy==0.12.2=py_0
  - conda-forge/noarch::pyspectral==0.10.1=py_0
  - conda-forge/linux-64::python-geotiepoints==1.2.0=py38h8790de6_0
  - conda-forge/noarch::rioxarray==0.1.0=py_0
  - conda-forge/noarch::satpy==0.23.0=py_0
  - conda-forge/linux-64::scikit-image==0.17.2=py38hc5bc63f_3
  - conda-forge/linux-64::scikit-learn==0.23.2=py38h519568a_1
  - conda-forge/linux-64::scipy==1.5.2=py38h8c5af15_2
  - conda-forge/noarch::sparse==0.11.2=py_0
  - conda-forge/noarch::xarray-spatial==0.1.1=pyh9f0ad1d_0
  - conda-forge/noarch::xcube==0.2.1=py_0
  - conda-forge/noarch::xesmf==0.3.0=py_0
  - conda-forge/noarch::xrft==0.2.2=pyh9f0ad1d_0
failed with initial frozen solve. Retrying with flexible solve.
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
```

But `mamba install parcels` works really quickly for me! Maybe @ocefpaf has some insight into whether we need to worry about mamba not doing consistent checks or if conda is just spinning its wheels to no end...

In any case, you can modify your class slightly as follows, which seems to work on the AWS cluster...
```python
import subprocess
import logging
from distributed import WorkerPlugin
from dask_gateway import GatewayCluster

class MambaPlugin(WorkerPlugin):
    """
    Install packages on a worker as it starts up.

    Parameters
    ----------
    packages : List[str]
        A list of packages to install with pip on startup.
    """
    def __init__(self, packages):
        self.packages = packages

    def setup(self, worker):
        logger = logging.getLogger("distributed.worker")
        subprocess.call(['mamba', 'install'] + self.packages)
        logger.info("Installed %s", self.packages)
```

**Comment by ocefpaf** [comment]
While mamba tries to be 100% compatible with conda, the solver is different. It is based on the cpp library libsolv. That solve is probably solid, unless there are package metadata problems in that mix.

Pinging @wolfv here b/c he can comment more on how mamba finds a solve when conda does not.

**Comment by jbusecke** [comment]
Ooooh amazing. I'll give that a go later today. Thanks for the quick help!

**Comment by wolfv** [comment]
yeah, we try to be as close as possible to conda. One difference is that we completely ignore track_features (except for priority purposes), and we always try to maximize the build number. So results sometimes differ, but most of the times there are always multiple valid solutions to a specific optimization problem...

If there is an issue, feel free to let us know on the mamba issue tracker.

**Comment by ocefpaf** [comment]
> we always try to maximize the build numbe

This is essential to get fixes on packages in conda-forge BTW! Highly recommend.

**Pull request merged**
