### PR TITLE
setup launch scripts for geyser/caldera

### PR DESCRIPTION
**Pull request by jhamman**
Added scripts for launching jupyer/dask on slurm for the geyser/caldera cluster. This doesn't work quite yet but I'm putting it up anyways.

### CODE REVIEW

**Comment by jhamman** [comment]
@davidedelvento - care to take a peak at the slurm components here?

**Comment by jedwards4b** [comment]
I think that all of these individual shell scripts with multiple hard coded values are a bad idea.  Would you consider PR #50 and the possibility of merging the cheyenne/geyser/caldera scripts into a smaller set of more flexible tools?

**Comment by jhamman** [comment]
@jedwards4b - certainly. I'll review your PR now. I think this gets to a broader question of if and to what extent these tools will be used and supported on Cheyenne. Is CISL considering making this sorts of tools available to a broader user group?

**Comment by davidedelvento** [comment]
@jhamman sure, when they are production ready. That is the reason why I got involved in the first place!

**Comment by jhamman** [comment]
@davidedelvento - great! How do should we define production ready?

**Comment by davidedelvento** [comment]
How about when @kmpaul deems it so? Maybe under the threaten than he'll get the user request for assistance? :-)

**Comment by jhamman** [comment]
I'm going to close this for now. CISL is still working on enabling port forwarding on Geyser/Caldera and until that happens, this is not worth pursuing.

**Pull request closed without merging**
