### PR TITLE
update ML working group zoom link

### PR DESCRIPTION
**Pull request by andersy005**
Cc @maxrjones / @weiji14  for visibility

### CODE REVIEW

**Comment by maxrjones** [comment]
thanks @andersy005! are you able to update the Pangeo calendar event?

**Review by weiji14 — APPROVED** [review]
Thanks @andersy005!

**Comment by andersy005** [comment]
> thanks @andersy005! are you able to update the Pangeo calendar event?

i don't think i have write access to the pangeo calendar event

**Comment by weiji14** [comment]
Maybe ask on https://discourse.pangeo.io/t/who-owns-pangeo-calendars/4430/7 if they could update calendar?

**Pull request closed without merging**
