### PR TITLE
provide IDs and links to individual datasets

### PR DESCRIPTION
**Pull request by rabernat**
I would like to be able to link to specific entries in the catalog. I believe this does that.

### CODE REVIEW

**Comment by rabernat** [comment]
I don't know. I haven't actually tried building it locally.

**Comment by martindurant** [comment]
OK, I only just twigged what you were doing here. This will be more useful as the catalog gains more entries. 
Might there be a reason at some point to split the cats into separate files and a hierarchy?

**Comment by rabernat** [comment]
Yes. I eventually imagine many sub-catalogs curated by the different sub-groups within pangeo, which are then aggregated into one big catalog.

**Comment by rabernat** [comment]
I guess I'll just merge an see how it looks.

**Comment by martindurant** [comment]
Anchors work, but there is excessive underlining.

**Pull request merged**
