### PR TITLE
Fix rst problems in cloud.rst

### PR DESCRIPTION
**Pull request by lesteve**
**Edit**: added following link + snapshot for clarification:
Looking at the `pangeo.io` doc (https://pangeo.io/setup_guides/cloud.html):

and seeing things like:
pangeo

It looks like something went slightly wrong in the rst at one point. You can see that in https://github.com/pangeo-data/pangeo/blob/master/docs/setup_guides/cloud.rst (search for `` `_ `` to look for problems).

I looked for similar problems with `git grep` and there were none left.

### CODE REVIEW

**Comment by arokem** [comment]
Looks like this would eliminate the links to the scripts on github?

**Comment by lesteve** [comment]
I was looking at the `pangeo.io` doc (https://pangeo.io/setup_guides/cloud.html):

and seeing things like:
pangeo

But looking at the readthedocs doc (https://pangeo.readthedocs.io/en/latest/setup_guides/cloud.html), the links seems fine.

Not sure the differences in how the two docs are generated ...

(from what I gathered I also learned a magical reST, or maybe sphinx, way of linking to a file plus including its content)

**Comment by arokem** [comment]
I think that the RTD version is out-dated. I don't think there's any magic there, it's just that the scripts are written out verbatim into that version of the docs. The goal of #402 was to avoid the duplication. Obviously, it seems to have introduced other issues... But unless I am missing something, I don't think that the current PR is a good solution to these issues, because it eliminates the links to GH.

**Comment by arokem** [comment]
Oh no - I am wrong. The links are defined at the bottom. 

+1 for this change!

**Comment by guillaumeeb** [comment]
I had no Idea there was still something on readthedocs. This does not sound normal.

Maybe open another issue and cc @rabernat.

**Pull request merged**
