### PR TITLE
Fix resources in .daskernetes.yaml file

### PR DESCRIPTION
**Pull request by mrocklin**
cc @rabernat you should make this change in your environment.

### CODE REVIEW

**Comment by rabernat** [comment]
Just so I understand...merging this PR will only cause this change to be applied to the `.daskernetes.yaml` file in *newly created* user home directories?

**Comment by mrocklin** [comment]
Correct, but you might consider applying this change to your
.daskernetes.yaml file as well

**Comment by jhamman** [comment]
@mrocklin - is this superseded by #115?

**Comment by mrocklin** [comment]
Yes, thanks for the reminder

**Pull request closed without merging**
