### PR TITLE
Update pangeo-showcase.rst

### PR DESCRIPTION
**Pull request by leslie-yoc**
Updating to include upcoming fall schedule and separate out recordings from last spring into their own section.

### CODE REVIEW

**Comment by rsignell-usgs** [comment]
@leslie-yoc , Steve & Shane from NOAA agreed yesterday to give their talk on the Environmental Data Retrieval API on 9/15 , right?

**Comment by leslie-yoc** [comment]
Ok so I am not sure if this worked, but I just went into my "patch-9" linked at the top and update the table to have Shane and Steve's names in the 9/15 slot. So now if we accept this pull request that should go through? If not let's just accept the pull request and then I'll fix it via my normal routine. Thanks!

**Comment by leslie-yoc** [comment]
@rsignell-usgs can you please review and then approve this pull request. I now have Shane and Steve in the table with the title of their talk. Once we get this live I'll advertise on Twitter.

**Comment by rabernat** [comment]
This looks great! Thanks Leslie!

**Pull request merged**
