### PR TITLE
Explicit invite for underrepresented people

### PR DESCRIPTION
**Pull request by niallrobinson**
I wondered if having an explicit invite to people to get involved displayed prominently would set a useful tone up front.

### CODE REVIEW

**Comment by niallrobinson** [comment]
NB i couldn't figure out how to build this locally so I don't know what it looks like

**Comment by rabernat** [comment]
I like the spirit of this. But I propose we have all language related to this topic vetted by a diversity expert.

> NB i couldn't figure out how to build this locally so I don't know what it looks like

You can infer the script from [.travis.yml](https://github.com/pangeo-data/pangeo/blob/master/.travis.yml)
```bash
cd docs
# make sure you have the necessary packages
pip install -r requirements.txt
# build
make html
```

**Comment by chiaral** [comment]
I can ask the diversity officer here at Lamont for input on the wording.

**Comment by niallrobinson** [comment]
> I propose we have all language related to this topic vetted by a diversity expert.

sounds good - I don't know how to do that 😄 Do you know someone we can refer to

For the record I've run it by our (gender diverse) group. I also tried to use http://www.hackerfactor.com/GenderGuesser.php but I think there isn't enough text.

**Comment by niallrobinson** [comment]
> I can ask the diversity officer here at Lamont for input on the wording.

! thanks

**Comment by niallrobinson** [comment]
this should probably also link to https://github.com/pangeo-data/governance/tree/master/conduct

**Pull request closed without merging**
