### PR TITLE
Create CODE_OF_CONDUCT.md

### PR DESCRIPTION
**Pull request by jhamman**

### CODE REVIEW

**Comment by jacobtomlinson** [comment]
GitHub have some good resources for this stuff.

https://opensource.guide/code-of-conduct/

**Comment by rabernat** [comment]
The master version of this should probably live in https://github.com/pangeo-data/governance

Do we also need a copy in each of our repos?

**Comment by jacobtomlinson** [comment]
@rabernat Maybe just reference it from each repo. Then changes only need to be made in one place.

**Comment by jhamman** [comment]
I'm going to close this for now. Interested parties should refer to the draft governance/conduct parties here: https://github.com/pangeo-data/governance/tree/master/conduct

**Pull request closed without merging**
