### PR TITLE
Add near-global cloud resolving simulation to catalog

### PR DESCRIPTION
**Pull request by nbren12**
This adds the 3D fields to the pangeo catalog. The surface and top of atmosphere
quantities will be uploaded at a later date.

### CODE REVIEW

**Comment by rabernat** [comment]
Noah, thanks so much for this!

It looks like we are getting a validation error on your entry:
https://travis-ci.org/pangeo-data/pangeo/builds/502724255?utm_source=github_status&utm_medium=notification

Have you verified that this entry works locally?

**Comment by nbren12** [comment]
No I haven't. Should I just install intake and try to load the catalog?

**Comment by rabernat** [comment]
Or you could just try adding the `driver` keyword and let travis re-try.

**Comment by nbren12** [comment]
okay done. let's see what travis thinks.

**Pull request merged**
